In [ ]:
import numpy as np
from google.colab import drive 
drive.mount('/content/gdrive')
data_path='/content/gdrive/MyDrive/EC247/'
from sklearn.model_selection import train_test_split
import torch


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:

X_test = np.load(data_path+"X_test.npy")
y_test = np.load(data_path+"y_test.npy")
person_train_valid = np.load(data_path+"person_train_valid.npy")
X_train_valid = np.load(data_path+"X_train_valid.npy")
y_train_valid = np.load(data_path+"y_train_valid.npy")
person_test = np.load(data_path+"person_test.npy")

In [ ]:
print ('Training/Valid data shape: {}'.format(X_train_valid.shape))
print ('Test data shape: {}'.format(X_test.shape))
print ('Training/Valid target shape: {}'.format(y_train_valid.shape))
print ('Test target shape: {}'.format(y_test.shape))
print ('Person train/valid shape: {}'.format(person_train_valid.shape))
print ('Person test shape: {}'.format(person_test.shape))


Training/Valid data shape: (2115, 22, 1000)
Test data shape: (443, 22, 1000)
Training/Valid target shape: (2115,)
Test target shape: (443,)
Person train/valid shape: (2115, 1)
Person test shape: (443, 1)


In [ ]:
# Exploring some parts of data 
verbose=True
if verbose:
  print(np.unique(person_test))
  print(np.unique(y_test))

#We need to convert y labels into 0-3 from 769-772 
y_train_valid=y_train_valid-769
y_test=y_test-769

if verbose:
  print(np.unique(y_test))



[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[769 770 771 772]
[0 1 2 3]


In [ ]:
# Function to split the given train_valid combination into training and validation in a 20% 80% split
# Input X_train_valid, y_train_valid, person_train_valid
# Output X_train, X_valid, y_train, y_valid, person_train, person_valid

def train_valid_split(X_train_valid,y_train_valid,person_train_valid):
    full_size=X_train_valid.shape[0]
    val_idxs=np.random.choice(int(full_size), int(0.2*full_size),replace=False)
    tr_idxs = np.array(list(set(range(full_size)).difference(set(val_idxs))))
    X_train=X_train_valid[tr_idxs]
    y_train=y_train_valid[tr_idxs]
    X_valid=X_train_valid[val_idxs]
    y_valid=y_train_valid[val_idxs]
    person_train=person_train_valid[tr_idxs]
    person_valid=person_train_valid[val_idxs]
    print(X_train.shape,y_train.shape,X_valid.shape,y_valid.shape,person_train.shape)
    return X_train,X_valid,y_train,y_valid,person_train,person_valid



In [ ]:
# Given a train and label arrays just return train and label arrays based on the person
# Input X,y, person_array,person
# Output X,y corresponding to that particular person

def make_subject_arr(X,y,person_array,person=0):
    pers_idx=np.argwhere(person_array.flatten()==person)
    X_person=X[pers_idx]
    y_person=y[pers_idx]
    return X_person,y_person


# Given a train and label arrays just return train and label arrays based on the one of the 4 tasks
# Input X,y, task [ 0-3]
# Output X,y corresponding to that particular task
def make_task_arr(X,y,task=0):
    task_idx=np.argwhere(y.flatten()==task)
    X_task=X[task_idx]
    y_task=y[task_idx]
    return X_task,y_task

